# -*- coding: utf-8 -*-
"""text_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X68cNjFBLLofWRs1nCSZeCohZffmm95u
"""

import os
os.kill(os.getpid(), 9)

import transformers
print(transformers.__version__)   # must print 4.41.2
from transformers import Trainer  # must not error
print("OK")

# ============================================================
# CELL 0 — Run this FIRST, then Runtime > Restart, then Cell 1
# ============================================================
!pip install -q --upgrade transformers==4.44.2 accelerate==0.33.0
!pip install -q torch scikit-learn matplotlib seaborn

# -*- coding: utf-8 -*-
"""
Enhanced DistilBERT — PART 1 (Version-safe, transformers==4.44.2)
20 Epochs - Optimized for No Training Loss (Smooth Convergence)
"""

import transformers, torch
print("transformers:", transformers.__version__)
print("torch       :", torch.__version__)
print("CUDA        :", torch.cuda.is_available())

import warnings, random
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns

from transformers import (
    DistilBertTokenizerFast,
    DistilBertModel,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
from transformers.modeling_outputs import SequenceClassifierOutput
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, roc_auc_score
)

# =============================
# STEP 1: Load Data
# =============================
df = pd.read_csv("text_dataset1.csv", encoding="latin1")
df = df[["Text", "label"]].dropna()
df["label"] = df["label"].map({"Non-ASD": 0, "ASD": 1})

print(f"\nTotal  : {len(df)}")
print(f"ASD    : {df['label'].sum()}")
print(f"Non-ASD: {(df['label']==0).sum()}")

# =============================
# STEP 2: Split 70 / 15 / 15
# =============================
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df["Text"].tolist(), df["label"].tolist(),
    test_size=0.30, stratify=df["label"], random_state=42
)
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels,
    test_size=0.50, stratify=temp_labels, random_state=42
)
print(f"\nTrain:{len(train_texts)} | Val:{len(val_texts)} | Test:{len(test_texts)}")

# =============================
# STEP 3: No augmentation
# =============================
all_train_texts  = train_texts
all_train_labels = train_labels
print(f"\nTrain (no augmentation): {len(all_train_texts)}")

# =============================
# STEP 4: Tokenizer
# =============================
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")
MAX_LEN   = 256

def tokenize(texts):
    return tokenizer(texts, padding=True, truncation=True, max_length=MAX_LEN)

train_encodings = tokenize(all_train_texts)
val_encodings   = tokenize(val_texts)
test_encodings  = tokenize(test_texts)

# =============================
# STEP 5: Dataset
# =============================
class ASD_Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = ASD_Dataset(train_encodings, all_train_labels)
val_dataset   = ASD_Dataset(val_encodings,   val_labels)
test_dataset  = ASD_Dataset(test_encodings,  test_labels)

# =============================
# STEP 6: Enhanced DistilBERT
# =============================
class EnhancedDistilBertClassifier(nn.Module):
    def __init__(self, num_labels=2, dropout_rate=0.3, label_smoothing=0.15):
        super().__init__()
        self.distilbert = DistilBertModel.from_pretrained(
            "distilbert-base-uncased",
            attn_implementation="eager"
        )
        hidden = self.distilbert.config.hidden_size  # 768

        # Unfreeze last 4 layers for better learning
        for name, p in self.distilbert.named_parameters():
            if any(f"transformer.layer.{i}" in name for i in [2, 3, 4, 5]):
                p.requires_grad = True
            else:
                p.requires_grad = False

        # Simplified head with gradient clipping friendly architecture
        self.pre_classifier = nn.Linear(hidden, hidden)
        self.layer_norm     = nn.LayerNorm(hidden)
        self.dropout1       = nn.Dropout(dropout_rate)
        self.intermediate   = nn.Linear(hidden, 256)
        self.activation     = nn.GELU()
        self.dropout2       = nn.Dropout(dropout_rate)
        self.classifier     = nn.Linear(256, num_labels)
        self.num_labels      = num_labels
        self.label_smoothing = label_smoothing

    def forward(self, input_ids=None, attention_mask=None,
                labels=None, output_attentions=False):
        out = self.distilbert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_attentions=output_attentions
        )
        x = out.last_hidden_state[:, 0]          # CLS
        x = self.activation(self.layer_norm(self.pre_classifier(x)))
        x = self.dropout1(x)
        x = self.activation(self.intermediate(x))
        x = self.dropout2(x)
        logits = self.classifier(x)

        loss = None
        if labels is not None:
            loss = nn.CrossEntropyLoss(
                label_smoothing=self.label_smoothing
            )(logits, labels)

        return SequenceClassifierOutput(
            loss=loss, logits=logits,
            hidden_states=out.hidden_states,
            attentions=out.attentions
        )

model = EnhancedDistilBertClassifier(num_labels=2, dropout_rate=0.3, label_smoothing=0.15)
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f"\nTrainable: {trainable:,} / {total:,} ({100*trainable/total:.1f}%)")

# =============================
# STEP 7: Training Arguments
# =============================
# Conservative warmup to prevent initial loss spikes
warmup = int(0.15 * 20 * len(train_dataset) / 16)  # 15% warmup for smooth start

training_args = TrainingArguments(
    output_dir              = "./results_enhanced_20epochs",
    evaluation_strategy     = "epoch",
    save_strategy           = "epoch",
    save_total_limit        = 3,  # Keep last 3 checkpoints

    # Conservative learning rate for stable training
    learning_rate           = 2.5e-5,  # Balanced for smooth convergence
    per_device_train_batch_size = 16,
    per_device_eval_batch_size  = 16,
    num_train_epochs        = 20,  # 20 epochs exactly

    # Regularization to prevent overfitting
    weight_decay            = 0.04,  # Moderate regularization
    warmup_steps            = warmup,
    lr_scheduler_type       = "cosine",  # Smooth decay

    # Model selection
    load_best_model_at_end  = True,
    metric_for_best_model   = "accuracy",
    greater_is_better       = True,

    # Logging
    logging_strategy        = "steps",
    logging_steps           = 20,
    report_to               = "none",

    # Performance
    fp16                    = torch.cuda.is_available(),

    # Gradient clipping to prevent exploding gradients
    max_grad_norm           = 1.0,

    # No early stopping - train full 20 epochs
)

# =============================
# STEP 8: Metrics
# =============================
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    probs = torch.softmax(torch.tensor(logits, dtype=torch.float), dim=1).numpy()[:, 1]
    acc   = accuracy_score(labels, preds)
    try:
        auc = roc_auc_score(labels, probs)
    except Exception:
        auc = 0.0
    return {"accuracy": round(acc, 4), "roc_auc": round(auc, 4)}

# =============================
# STEP 9: Trainer
# =============================
trainer = Trainer(
    model           = model,
    args            = training_args,
    train_dataset   = train_dataset,
    eval_dataset    = val_dataset,
    compute_metrics = compute_metrics,
    # No early stopping callback to ensure 20 complete epochs
)

# =============================
# STEP 10: Train for 20 Epochs
# =============================
print("\n" + "="*60)
print("TRAINING CONFIGURATION")
print("="*60)
print(f"Training epochs: 20 (full training, no early stopping)")
print(f"Learning rate: 2.5e-5 with cosine decay")
print(f"Warmup steps: {warmup} (15% of total)")
print(f"Weight decay: 0.04")
print(f"Dropout: 0.3")
print(f"Label smoothing: 0.15")
print(f"Unfrozen layers: 2, 3, 4, 5 (4 layers)")
print(f"Gradient clipping: 1.0")
print("="*60 + "\n")

print("Training for 20 epochs - Monitoring for smooth loss convergence...")
trainer.train()

# =============================
# STEP 11: Test Evaluation
# =============================
device      = torch.device("cuda" if torch.cuda.is_available() else "cpu")
label_names = ["Non-ASD", "ASD"]
model.to(device)
model.eval()

out    = trainer.predict(test_dataset)
y_pred = np.argmax(out.predictions, axis=1)
y_prob = torch.softmax(
    torch.tensor(out.predictions, dtype=torch.float), dim=1
).numpy()[:, 1]

final_acc = accuracy_score(test_labels, y_pred)
final_auc = roc_auc_score(test_labels, y_prob) if len(np.unique(test_labels)) > 1 else 0.0

print("\n" + "="*60)
print("TEST RESULTS AFTER 20 EPOCHS")
print("="*60)
print(f"Accuracy : {final_acc:.4f} ({final_acc*100:.1f}%)")
print(f"ROC-AUC  : {final_auc:.4f}")
print()
print(classification_report(test_labels, y_pred, target_names=label_names))

# Target check
if final_acc >= 0.91:
    print(f"\n🎉 TARGET ACHIEVED! Accuracy: {final_acc*100:.1f}% (≥91%)")
elif final_acc >= 0.90:
    print(f"\n✓ Close to target! Accuracy: {final_acc*100:.1f}%")
else:
    print(f"\n⚠ Current accuracy: {final_acc*100:.1f}%")

# =============================
# STEP 12: Visualizations (Checking for No Training Loss Issues)
# =============================

# Confusion matrix
cm = confusion_matrix(test_labels, y_pred)
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Confusion Matrix
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=label_names, yticklabels=label_names, ax=axes[0,0])
axes[0,0].set_title(f'Confusion Matrix\nAccuracy: {final_acc*100:.1f}%', fontsize=12, fontweight='bold')
axes[0,0].set_ylabel('True')
axes[0,0].set_xlabel('Predicted')

# Training Curves
logs = trainer.state.log_history
train_loss = [(e["epoch"], e["loss"]) for e in logs if "loss" in e and "eval_loss" not in e]
val_loss = [(e["epoch"], e["eval_loss"]) for e in logs if "eval_loss" in e]
val_acc = [(e["epoch"], e["eval_accuracy"]) for e in logs if "eval_accuracy" in e]

if train_loss:
    epochs_t, loss_t = zip(*train_loss)
    axes[0,1].plot(epochs_t, loss_t, color="#378ADD", linewidth=2, label='Training Loss', marker='o', markersize=3)

if val_loss:
    epochs_vl, loss_v = zip(*val_loss)
    axes[0,1].plot(epochs_vl, loss_v, color="#D85A30", linewidth=2, label='Validation Loss', marker='s', markersize=3)

axes[0,1].set_xlabel('Epoch', fontsize=11)
axes[0,1].set_ylabel('Loss', fontsize=11)
axes[0,1].set_title('Loss Curves (20 Epochs)', fontsize=12, fontweight='bold')
axes[0,1].legend()
axes[0,1].grid(True, alpha=0.3)
axes[0,1].spines[["top","right"]].set_visible(False)

# Check for loss issues
if train_loss:
    final_train_loss = train_loss[-1][1] if train_loss else 0
    final_val_loss = val_loss[-1][1] if val_loss else 0
    loss_status = "✓ Normal" if final_train_loss < 0.5 else "⚠ Check"
    axes[0,1].text(0.02, 0.98, f'Final Train Loss: {final_train_loss:.4f}\nFinal Val Loss: {final_val_loss:.4f}',
                   transform=axes[0,1].transAxes, fontsize=9, verticalalignment='top',
                   bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

# Validation Accuracy
if val_acc:
    epochs_va, acc_vals = zip(*val_acc)
    axes[1,0].plot(epochs_va, acc_vals, color="#1D9E75", linewidth=2, label='Validation Accuracy', marker='o', markersize=3)
    axes[1,0].axhline(y=0.91, color='red', linestyle='--', linewidth=1, label='Target (91%)')
    axes[1,0].set_xlabel('Epoch', fontsize=11)
    axes[1,0].set_ylabel('Accuracy', fontsize=11)
    axes[1,0].set_title('Validation Accuracy (20 Epochs)', fontsize=12, fontweight='bold')
    axes[1,0].legend()
    axes[1,0].grid(True, alpha=0.3)
    axes[1,0].spines[["top","right"]].set_visible(False)
    axes[1,0].set_ylim(0.5, 1.0)

# Metrics Bar Chart
metrics = ['Accuracy', 'ROC-AUC']
values = [final_acc, final_auc]
colors_bar = ['#1D9E75', '#378ADD']
bars = axes[1,1].bar(metrics, values, color=colors_bar, edgecolor='black', linewidth=1.5)
for bar, val in zip(bars, values):
    axes[1,1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                   f'{val:.3f}', ha='center', va='bottom', fontweight='bold')
axes[1,1].set_ylim(0, 1.1)
axes[1,1].set_ylabel('Score', fontsize=11)
axes[1,1].set_title('Test Performance (20 Epochs)', fontsize=12, fontweight='bold')
axes[1,1].grid(True, alpha=0.3, axis='y')

plt.suptitle('Enhanced DistilBERT - 20 Epoch Training Results', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('training_results_20epochs.png', dpi=150, bbox_inches='tight')
plt.show()

# =============================
# STEP 13: Loss Summary Report
# =============================
print("\n" + "="*60)
print("TRAINING SUMMARY - 20 EPOCHS")
print("="*60)

if train_loss:
    initial_loss = train_loss[0][1]
    final_loss = train_loss[-1][1]
    loss_reduction = ((initial_loss - final_loss) / initial_loss) * 100

    print(f"Training Loss Progression:")
    print(f"  Epoch 1  Loss: {initial_loss:.4f}")
    print(f"  Epoch 20 Loss: {final_loss:.4f}")
    print(f"  Reduction: {loss_reduction:.1f}%")

    if loss_reduction > 50:
        print(f"  ✓ Status: Normal loss convergence")
    else:
        print(f"  ⚠ Status: Check for learning issues")

if val_loss:
    final_val_loss = val_loss[-1][1]
    print(f"\nValidation Loss: {final_val_loss:.4f}")

print(f"\nFinal Test Accuracy: {final_acc*100:.1f}%")
print(f"Final Test ROC-AUC: {final_auc:.4f}")

# Save model
trainer.save_model("./enhanced_distilbert_20epochs")
tokenizer.save_pretrained("./enhanced_distilbert_20epochs")
print(f"\n✓ Model saved to './enhanced_distilbert_20epochs'")
print("✓ Results saved to 'training_results_20epochs.png'")

print("\n" + "="*60)
print("Part 1 Complete - 20 Epochs Finished")
print("Training loss should show smooth, consistent decrease")
print("Run Part 2 for XAI + Ensemble")
print("="*60)

# -*- coding: utf-8 -*-
"""
Enhanced DistilBERT — PART 2: XAI + Ensemble
Run AFTER Part 1. All variables (model, tokenizer, device, splits) carry over.

XAI method: Integrated Gradients via captum (no SHAP — avoids transformers conflict)
             + Attention Heatmaps
Ensemble   : Enhanced DistilBERT + TF-IDF Logistic Regression (soft voting)
"""

# =============================
# Install (run once in Colab)
# !pip install captum -q
# =============================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
import matplotlib.patches as mpatches

from captum.attr import LayerIntegratedGradients
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Confirm device & model are ready
print("Device:", device)
print("Model eval mode:", not model.training)

# =============================
# STEP 11: XAI — Attention Heatmap
# =============================
def plot_attention_heatmap(text, layer=-1, head=0, save_path="attention_heatmap.png"):
    """
    Plot token-to-token attention weights for a given input text.
    layer : transformer layer index (-1 = last layer)
    head  : attention head index (0–5 for DistilBERT)
    """
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_LEN
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs, output_attentions=True)

    attentions = outputs.attentions
    if attentions is None:
        print("ERROR: attentions is None. Ensure attn_implementation='eager'.")
        return

    # attentions: tuple of (num_layers,) → each (batch, heads, seq, seq)
    attn_matrix = attentions[layer][0, head].cpu().numpy()  # (seq, seq)

    tokens     = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0].cpu())
    actual_len = int((inputs["attention_mask"][0] == 1).sum().item())
    tokens     = tokens[:actual_len]
    attn_matrix = attn_matrix[:actual_len, :actual_len]

    fig_size = max(8, actual_len // 2)
    plt.figure(figsize=(fig_size, fig_size))
    sns.heatmap(
        attn_matrix,
        xticklabels=tokens,
        yticklabels=tokens,
        cmap="viridis",
        linewidths=0.3,
        vmin=0, vmax=attn_matrix.max()
    )
    plt.title(f"Attention Heatmap  |  Layer {layer}  |  Head {head}", fontsize=13)
    plt.xticks(rotation=90, fontsize=8)
    plt.yticks(rotation=0,  fontsize=8)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"Saved: {save_path}")

sample_text = "My child avoids eye contact and prefers to play alone for long periods."
plot_attention_heatmap(sample_text, layer=-1, head=0)

# Plot all 6 heads for the last layer side-by-side
def plot_all_heads(text, layer=-1, save_path="attention_all_heads.png"):
    inputs = tokenizer(text, return_tensors="pt",
                       truncation=True, max_length=MAX_LEN).to(device)
    with torch.no_grad():
        outputs = model(**inputs, output_attentions=True)

    attentions  = outputs.attentions[layer][0].cpu().numpy()  # (heads, seq, seq)
    tokens      = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0].cpu())
    actual_len  = int((inputs["attention_mask"][0] == 1).sum().item())
    tokens      = tokens[:actual_len]
    num_heads   = attentions.shape[0]

    fig, axes = plt.subplots(2, num_heads // 2, figsize=(20, 8))
    axes = axes.flatten()
    for h in range(num_heads):
        sns.heatmap(
            attentions[h, :actual_len, :actual_len],
            ax=axes[h], cmap="viridis",
            xticklabels=tokens, yticklabels=tokens,
            cbar=False, linewidths=0.2
        )
        axes[h].set_title(f"Head {h}", fontsize=9)
        axes[h].tick_params(labelsize=6, rotation=90)

    fig.suptitle(f"All Attention Heads — Layer {layer}", fontsize=13)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"Saved: {save_path}")

plot_all_heads(sample_text, layer=-1)

# =============================
# STEP 12: XAI — Integrated Gradients (captum)
# Replaces SHAP — no version conflicts
# =============================
print("\nComputing Integrated Gradients explanations...")

def get_embeddings(input_ids):
    """Return the word embedding layer output."""
    return model.distilbert.embeddings.word_embeddings(input_ids)

def ig_forward(input_embeds, attention_mask, target_class):
    """Forward pass through the model using input embeddings directly."""
    distilbert_out = model.distilbert(
        inputs_embeds=input_embeds,
        attention_mask=attention_mask
    )
    hidden = distilbert_out.last_hidden_state[:, 0]

    x = model.pre_classifier(hidden)
    x = model.layer_norm(x)
    x = model.dropout1(x)
    x = model.activation(x)
    x = model.intermediate(x)
    x = model.activation(x)
    x = model.dropout2(x)
    logits = model.classifier(x)

    probs = torch.softmax(logits, dim=1)
    return probs[:, target_class]

def explain_with_ig(text, target_class=1, n_steps=50):
    """
    Compute token-level attributions using Integrated Gradients.
    target_class: 0=Non-ASD, 1=ASD
    Returns tokens and their attribution scores.
    """
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_LEN
    ).to(device)

    input_ids      = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]
    input_embeds   = get_embeddings(input_ids)

    # Baseline: all [PAD] token embeddings
    baseline_ids     = torch.zeros_like(input_ids)
    baseline_embeds  = get_embeddings(baseline_ids)

    # Interpolate between baseline and input
    attributions = torch.zeros_like(input_embeds)
    for alpha in np.linspace(0, 1, n_steps):
        interp = baseline_embeds + alpha * (input_embeds - baseline_embeds)
        interp = interp.detach().requires_grad_(True)

        score = ig_forward(interp, attention_mask, target_class)
        score.backward()

        attributions += interp.grad.detach()

    attributions = (input_embeds - baseline_embeds) * (attributions / n_steps)
    # Summarise per token: L2 norm across embedding dim
    token_attrs = attributions[0].norm(dim=-1).cpu().numpy()

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0].cpu())
    actual_len  = int((attention_mask[0] == 1).sum().item())
    tokens      = tokens[:actual_len]
    token_attrs = token_attrs[:actual_len]

    return tokens, token_attrs

def plot_ig_attributions(text, target_class=1, save_path="ig_attributions.png"):
    label_map = {0: "Non-ASD", 1: "ASD"}
    tokens, attrs = explain_with_ig(text, target_class=target_class)

    # Normalize
    norm_attrs = attrs / (attrs.max() + 1e-8)

    colors = ["#d73027" if v > 0 else "#4575b4" for v in norm_attrs]

    fig, ax = plt.subplots(figsize=(max(10, len(tokens) * 0.6), 3))
    bars = ax.bar(range(len(tokens)), norm_attrs, color=colors, edgecolor="none")
    ax.set_xticks(range(len(tokens)))
    ax.set_xticklabels(tokens, rotation=75, ha="right", fontsize=9)
    ax.set_ylabel("Attribution score (normalised)", fontsize=10)
    ax.set_title(
        f"Integrated Gradients — target: {label_map[target_class]}\n\"{text[:80]}...\"",
        fontsize=11
    )
    ax.axhline(0, color="black", linewidth=0.5)

    red_patch  = mpatches.Patch(color="#d73027", label=f"Supports {label_map[target_class]}")
    blue_patch = mpatches.Patch(color="#4575b4", label="Against")
    ax.legend(handles=[red_patch, blue_patch], fontsize=9)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"Saved: {save_path}")

# Explain a few examples
examples = [
    ("My child avoids eye contact and prefers to play alone for long periods.", 1),
    ("My child enjoys playing with friends and responds to their name.", 0),
    ("They have difficulty transitioning between tasks and get very upset at changes.", 1),
]

for txt, cls in examples:
    plot_ig_attributions(txt, target_class=cls,
                         save_path=f"ig_attr_class{cls}.png")

print("Integrated Gradients explanations done.")

# =============================
# STEP 13: Inference Helper
# =============================
def predict_text(text, verbose=True):
    inputs = tokenizer(
        text, padding=True, truncation=True,
        max_length=MAX_LEN, return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        logits  = outputs.logits
        pred    = torch.argmax(logits, dim=1).item()
        probs   = torch.softmax(logits, dim=1)[0]

    label_map = {0: "Non-ASD", 1: "ASD"}
    if verbose:
        print(f"\nText       : {text}")
        print(f"Prediction : {label_map[pred]}")
        print(f"Confidence : {probs[pred].item():.4f}")
        print(f"  Non-ASD  : {probs[0].item():.4f}  |  ASD : {probs[1].item():.4f}")

    return pred, probs.cpu().numpy()

predict_text("My child avoids eye contact and prefers to play alone for long periods.")
predict_text("My child enjoys playing with friends and responds to their name.")

# =============================
# STEP 14: ENSEMBLE
# Enhanced DistilBERT + TF-IDF Logistic Regression — Soft Voting
# =============================
print("\n===== ENSEMBLE: Enhanced DistilBERT + TF-IDF LR =====")

# --- 14a: Train TF-IDF + LR ---
tfidf_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), max_features=10000)),
    ("clf",   LogisticRegression(max_iter=1000, C=1.0, class_weight="balanced"))
])
tfidf_pipeline.fit(train_texts, train_labels)
print("TF-IDF + LR trained.")

# --- 14b: Get DistilBERT probs on test set ---
def get_bert_probs(texts, batch_size=16):
    all_probs = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(
            batch, padding=True, truncation=True,
            max_length=MAX_LEN, return_tensors="pt"
        ).to(device)
        with torch.no_grad():
            logits = model(**enc).logits
            probs  = torch.softmax(logits, dim=1).cpu().numpy()
        all_probs.append(probs)
    return np.vstack(all_probs)

bert_probs  = get_bert_probs(test_texts)           # (N, 2)
tfidf_probs = tfidf_pipeline.predict_proba(test_texts)  # (N, 2)

# --- 14c: Weighted soft vote ---
BERT_WEIGHT = 0.65
LR_WEIGHT   = 0.35

ensemble_probs = BERT_WEIGHT * bert_probs + LR_WEIGHT * tfidf_probs
ensemble_preds = np.argmax(ensemble_probs, axis=1)

bert_acc     = accuracy_score(test_labels, np.argmax(bert_probs, axis=1))
tfidf_acc    = accuracy_score(test_labels, tfidf_pipeline.predict(test_texts))
ensemble_acc = accuracy_score(test_labels, ensemble_preds)

print(f"\nModel accuracies on test set:")
print(f"  Enhanced DistilBERT  : {bert_acc:.4f}")
print(f"  TF-IDF + LR          : {tfidf_acc:.4f}")
print(f"  ENSEMBLE (weighted)  : {ensemble_acc:.4f}")

print("\n===== ENSEMBLE Classification Report =====")
print(classification_report(test_labels, ensemble_preds, target_names=label_names))

# Accuracy comparison bar chart
fig, ax = plt.subplots(figsize=(7, 4))
bars = ax.bar(
    ["Enhanced DistilBERT", "TF-IDF + LR", "Ensemble"],
    [bert_acc, tfidf_acc, ensemble_acc],
    color=["#378ADD", "#888780", "#1D9E75"],
    width=0.5, edgecolor="none"
)
for bar, val in zip(bars, [bert_acc, tfidf_acc, ensemble_acc]):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f"{val:.4f}", ha="center", va="bottom", fontsize=11, fontweight="bold")
ax.set_ylim(0, 1.1)
ax.set_ylabel("Accuracy")
ax.set_title("Model Comparison — Test Accuracy")
ax.spines[["top","right"]].set_visible(False)
plt.tight_layout()
plt.savefig("model_comparison.png", dpi=150)
plt.show()
print("Saved: model_comparison.png")

# Ensemble Confusion Matrix
cm_ens = confusion_matrix(test_labels, ensemble_preds)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_ens, annot=True, fmt="d", cmap="Greens",
            xticklabels=label_names, yticklabels=label_names)
plt.title("Ensemble — Confusion Matrix")
plt.ylabel("True"); plt.xlabel("Predicted")
plt.tight_layout()
plt.savefig("confusion_matrix_ensemble.png", dpi=150)
plt.show()
print("Saved: confusion_matrix_ensemble.png")

# =============================
# STEP 15: Ensemble Inference
# =============================
def predict_ensemble(text, verbose=True):
    _, bert_p = predict_text(text, verbose=False)
    lr_p      = tfidf_pipeline.predict_proba([text])[0]

    combined  = BERT_WEIGHT * bert_p + LR_WEIGHT * lr_p
    pred      = np.argmax(combined)
    label_map = {0: "Non-ASD", 1: "ASD"}

    if verbose:
        print(f"\nText              : {text}")
        print(f"Ensemble Result   : {label_map[pred]}")
        print(f"  Non-ASD prob    : {combined[0]:.4f}")
        print(f"  ASD prob        : {combined[1]:.4f}")
        print(f"  (BERT {BERT_WEIGHT} + LR {LR_WEIGHT} weighted)")

    return label_map[pred], combined

# Demo
print("\n--- Ensemble Inference Demos ---")
predict_ensemble("My child rarely makes eye contact, prefers to spin wheels on toys for hours, and becomes extremely distressed when routines are changed.")
predict_ensemble("The toddler doesn't respond to their name, avoids playing with other children, and lines up blocks in perfect rows instead of stacking them.")
predict_ensemble("He is very particular about food textures and sounds, but communicates well and shows affection to family members.")
predict_ensemble("My son has significant language delay, repeats phrases out of context, and flaps his hands when excited or upset.")